name: gaussian_splatting
channels:
  - defaults
  - conda-forge
  - nvidia/label/cuda-12.8.0
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40.0=hc2dff05_2
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - cuda-cccl_linux-64=12.8.55=0
  - cuda-command-line-tools=12.8.0=0
  - cuda-compiler=12.8.0=0
  - cuda-crt-dev_linux-64=12.8.61=0
  - cuda-crt-tools=12.8.61=0
  - cuda-cudart=12.8.57=0
  - cuda-cudart-dev=12.8.57=0
  - cuda-cudart-dev_linux-64=12.8.57=0
  - cuda-cudart-static=12.8.57=0
  - cuda-cudart-static_linux-64=12.8.57=0
  - cuda-cudart_linux-64=12.8.57=0
  - cuda-cuobjdump=12.8.55=0
  - cuda-cupti=12.8.57=0
  - cuda-cupti-dev=12.8.57=0
  - cuda-cuxxfilt=12.8.55=0
  - cuda-driver-dev=12.8.57=0
  - cuda-driver-dev_linux-64=12.8.57=0
  - cuda-gdb=12.8.55=0
  - cuda-libraries=12.8.0=0
  - cuda-libraries-dev=12.8.0=0
  - cuda-nsight=12.8.55=0
  - cuda-nvcc=12.8.61=0
  - cuda-nvcc-dev_linux-64=12.8.61=0
  - cuda-nvcc-impl=12.8.61=0
  - cuda-nvcc-tools=12.8.61=0
  - cuda-nvcc_linux-64=12.8.61=0
  - cuda-nvdisasm=12.8.55=0
  - cuda-nvml-dev=12.8.55=0
  - cuda-nvprof=12.8.57=0
  - cuda-nvprune=12.8.55=0
  - cuda-nvrtc=12.8.61=0
  - cuda-nvrtc-dev=12.8.61=0
  - cuda-nvtx=12.8.55=0
  - cuda-nvvm-dev_linux-64=12.8.61=0
  - cuda-nvvm-impl=12.8.61=0
  - cuda-nvvm-tools=12.8.61=0
  - cuda-nvvp=12.8.57=0
  - cuda-opencl=12.8.55=0
  - cuda-opencl-dev=12.8.55=0
  - cuda-profiler-api=12.8.55=0
  - cuda-sanitizer-api=12.8.55=0
  - cuda-toolkit=12.8.0=0
  - cuda-tools=12.8.0=0
  - cuda-version=12.8=h30beaf8_3
  - cuda-visual-tools=12.8.0=0
  - dbus=1.16.2=h5bd4931_0
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.13.3=h4a9f257_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_2
  - gds-tools=1.13.0.11=0
  - gmp=6.3.0=h6a678d5_0
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_2
  - icu=73.1=h6a678d5_0
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - ld_impl_linux-64=2.40=h12ee557_0
  - libblas=3.9.0=38_h4a7cf45_openblas
  - libcblas=3.9.0=38_h0358290_openblas
  - libcublas=12.8.3.14=0
  - libcublas-dev=12.8.3.14=0
  - libcufft=11.3.3.41=0
  - libcufft-dev=11.3.3.41=0
  - libcufile=1.13.0.11=0
  - libcufile-dev=1.13.0.11=0
  - libcurand=10.3.9.55=0
  - libcurand-dev=10.3.9.55=0
  - libcusolver=11.7.2.55=0
  - libcusolver-dev=11.7.2.55=0
  - libcusparse=12.5.7.53=0
  - libcusparse-dev=12.5.7.53=0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libglib=2.84.4=h77a78f3_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - liblapack=3.9.0=38_h47877c9_openblas
  - libnpp=12.3.3.65=0
  - libnpp-dev=12.3.3.65=0
  - libnsl=2.0.0=h5eee18b_0
  - libnvfatbin=12.8.55=0
  - libnvfatbin-dev=12.8.55=0
  - libnvjitlink=12.8.61=1
  - libnvjitlink-dev=12.8.61=1
  - libnvjpeg=12.3.5.57=0
  - libnvjpeg-dev=12.3.5.57=0
  - libopenblas=0.3.30=h46f56fc_0
  - libpng=1.6.50=h2ed474d_0
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - nsight-compute=2025.1.0.14=0
  - nspr=4.37=h8459abe_0
  - nss=3.117=h3135ca0_0
  - numpy=1.22.3=py310h4ef5377_2
  - ocl-icd=2.3.2=h5eee18b_1
  - openssl=3.0.18=hd6dcaed_0
  - pcre2=10.46=hf426167_0
  - pip=25.2=pyhc872135_1
  - plyfile=1.1=pyhd8ed1ab_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - python_abi=3.10=2_cp310
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - sysroot_linux-64=2.17=h57e8cba_10
  - tk=8.6.15=h54e0aa7_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310h06a4308_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - contourpy==1.3.2
      - cycler==0.12.1
      - filelock==3.19.1
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - networkx==3.3
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - packaging==25.0
      - pillow==11.3.0
      - pyparsing==3.2.5
      - six==1.17.0
      - submodules/diff-gaussian-rasterization
      - submodules/simple-knn
      - submodules/fused-ssim
      - sympy==1.14.0
      - torch==2.8.0+cu128
      - torchaudio==2.8.0+cu128
      - torchvision==0.23.0+cu128
      - triton==3.4.0
      - typing-extensions==4.15.0
prefix: /home/christoa/miniconda3/envs/gaussian_splatting
